---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: complete-security-pipeline
  namespace: cicd
spec:
  params:
  - name: git-url
    type: string
    default: https://github.com/yourusername/openshift-security-project.git
  - name: git-revision
    type: string
    default: main
  - name: image-name
    type: string
    default: vulnerable-app
  - name: namespace
    type: string
    default: security-demo
  
  workspaces:
  - name: shared-workspace
  
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: deleteExisting
      value: "true"
    workspaces:
    - name: output
      workspace: shared-workspace
  
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.image-name):$(params.git-revision)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: application/vulnerable-app
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  
  - name: deploy
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
    - name: SCRIPT
      value: |
        oc set image deployment/$(params.image-name) \
          $(params.image-name)=image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.image-name):$(params.git-revision) \
          -n $(params.namespace)
        oc rollout status deployment/$(params.image-name) -n $(params.namespace)
    runAfter:
    - build-image
  
  - name: verify-deployment
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
    - name: SCRIPT
      value: |
        oc wait --for=condition=available --timeout=300s deployment/$(params.image-name) -n $(params.namespace)
        oc get pods -n $(params.namespace) -l app=$(params.image-name)
    runAfter:
    - deploy
  
  - name: tag-latest
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
    - name: SCRIPT
      value: |
        oc tag $(params.namespace)/$(params.image-name):$(params.git-revision) \
               $(params.namespace)/$(params.image-name):latest \
               -n $(params.namespace)
    runAfter:
    - verify-deployment
