---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-workspace
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: cicd
data:
  run-pipeline.sh: |
    #!/bin/bash
    tkn pipeline start complete-security-pipeline \
      -n cicd \
      -s pipeline-sa \
      --workspace name=shared-workspace,claimName=pipeline-workspace \
      --showlog

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: integration-test
  namespace: cicd
spec:
  params:
  - name: namespace
    type: string
  - name: app-name
    type: string
  steps:
  - name: test
    image: curlimages/curl:latest
    script: |
      #!/bin/sh
      set -e
      echo "Running integration tests for $(params.app-name) in $(params.namespace)"
      echo "Tests would run here"
      echo "Integration tests passed"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: notify-success
  namespace: cicd
spec:
  params:
  - name: message
    type: string
  steps:
  - name: notify
    image: curlimages/curl:latest
    script: |
      #!/bin/sh
      echo "Notification: $(params.message)"
      echo "Would send notification to Slack/Email"
