---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulnerable-app
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/openshift-security-project.git
    targetRevision: main
    path: application/vulnerable-app
  destination:
    server: https://kubernetes.default.svc
    namespace: security-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
