---
apiVersion: v1
kind: Namespace
metadata:
  name: security-demo
  labels:
    name: security-demo

---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    name: cicd

---
apiVersion: v1
kind: Namespace
metadata:
  name: security-tools
  labels:
    name: security-tools

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-demo-quota
  namespace: security-demo
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    persistentvolumeclaims: "2"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cicd-quota
  namespace: cicd
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    persistentvolumeclaims: "3"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-tools-quota
  namespace: security-tools
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    persistentvolumeclaims: "3"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-demo-limits
  namespace: security-demo
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 1Gi
    min:
      cpu: 25m
      memory: 32Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cicd-limits
  namespace: cicd
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 1Gi
    min:
      cpu: 25m
      memory: 32Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-tools-limits
  namespace: security-tools
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 1Gi
    min:
      cpu: 25m
      memory: 32Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    type: Container
