---
apiVersion: v1
kind: Namespace
metadata:
  name: security-demo
  labels:
    name: security-demo
    app: vulnerable-app

---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    name: cicd
    purpose: ci-cd

---
apiVersion: v1
kind: Namespace
metadata:
  name: security-tools
  labels:
    name: security-tools
    purpose: security

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-demo-quota
  namespace: security-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "3"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cicd-quota
  namespace: cicd
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-tools-quota
  namespace: security-tools
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-demo-limits
  namespace: security-demo
spec:
  limits:
  - max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cicd-limits
  namespace: cicd
spec:
  limits:
  - max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container

---
apiVersion: v1
kind: LimitRange
metadata:
  name: security-tools-limits
  namespace: security-tools
spec:
  limits:
  - max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
