apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy-minimal
  namespace: cicd
spec:
  params:
  - name: image-name
    type: string
    default: vulnerable-app

  - name: namespace
    type: string
    default: security-demo

  workspaces:
  - name: shared-workspace

  tasks:
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
      apiVersion: tekton.dev/v1
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.image-name):latest
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: .
    workspaces:
    - name: source
      workspace: shared-workspace

  - name: deploy
    runAfter:
    - build-image
    taskRef:
      name: openshift-client
      kind: ClusterTask
      apiVersion: tekton.dev/v1
    params:
    - name: SCRIPT
      value: |
        oc set image deployment/$(params.image-name) \
          $(params.image-name)=image-registry.openshift-image-registry.svc:5000/$(params.namespace)/$(params.image-name):latest \
          -n $(params.namespace)

        oc rollout status deployment/$(params.image-name) \
          -n $(params.namespace) --timeout=3m

