---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: cicd
spec:
  serviceAccountName: pipeline-sa
  triggers:
  - name: github-push
    bindings:
    - ref: github-push-binding
    template:
      ref: build-trigger-template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: cicd
spec:
  params:
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-trigger-template
  namespace: cicd
spec:
  params:
  - name: git-url
  - name: git-revision
    default: main
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: build-run-
      namespace: cicd
    spec:
      pipelineRef:
        name: build-and-deploy-minimal
      params:
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-revision
        value: $(tt.params.git-revision)
      workspaces:
      - name: shared-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      serviceAccountName: pipeline-sa

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-webhook
  namespace: cicd
spec:
  to:
    kind: Service
    name: el-github-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
